### PR TITLE
Ensure we pass needed environment in edpm_deploy

### PR DESCRIPTION
**Pull request by cjeanner**
As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
We don't have the error anymore for that task:
https://review.rdoproject.org/zuul/build/b2727aed63dc4dc3b5d24dbe849aa0ed/log/ci-framework-data/logs/ansible.log-2023-07-20-22:57#1910

Still, we apparently lack the actual output.... Might be nice to redirect the command stdout to `|tee -a {{ cifmw_edpm_deploy_basedir }}/logs/<some-file>.log` or something like that.

**Review by raukadah — APPROVED** [review]
/approve

**Pull request merged**
