### PR TITLE
Replace jmspath query with a native Ansible one

### PR DESCRIPTION
**Pull request by pablintino**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:

### CODE REVIEW

**Comment by pablintino** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Review by raukadah — APPROVED** [review]
tested locally, works locally and passes the same in molecule test

**Pull request merged**
