### PR TITLE
Removed custom patch since the upstream pr has been merged

### PR DESCRIPTION
**Pull request by rebtoor**
The mentioned upstream PR https://github.com/openshift-metal3/dev-scripts/pull/1607 has been merged, so this patch shouldn't be needed anymore. 

Thx to @rabi for reporting it.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2133

### CODE REVIEW

**Review by raukadah — COMMENTED** [review]
/approve
/lgtm

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
/unhold 

ds test are fine

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

Added Depends-On

**Pull request merged**
