### PR TITLE
Revert "[must-gather] Drop our custom log collection in favor of must-gather"

### PR DESCRIPTION
**Pull request by lewisdenny**
Reverts openstack-k8s-operators/ci-framework#857

This revert is just for testing purpose.

### CODE REVIEW

**Comment by marios** [comment]
@lewisdenny is this ready for review ? I guess not based on the description above but ci bot assigned me for review and it showed up in my notifications.

can you please set to draft ? Or, do we really want to revert and if so why?

**Comment by lewisdenny** [comment]
recheck

**Comment by cjeanner** [comment]
@lewisdenny is this still needed for your tests? Or can we close it? :)

**Pull request closed without merging**
