### PR TITLE
Add new logo to the project

### PR DESCRIPTION
**Pull request by cjeanner**
As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running
- [X] Appropriate documentation exists and/or is up-to-date:

### CODE REVIEW

**Comment by cjeanner** [comment]
recheck

**Review by dasm — APPROVED** [review]
/lgtm

**Comment by viroel** [comment]
the font is not properly set in these logos, maybe you don't have it installed in your env?
@cjeanner do you want me to generate those images for you?

**Comment by viroel** [comment]
@cjeanner pls check the shared drive

**Comment by cjeanner** [comment]
/unhold

Logos are now correctly displayed.

**Comment by cjeanner** [comment]
recheck

**Pull request merged**
