### PR TITLE
Improve values.yaml generators

### PR DESCRIPTION
**Pull request by cjeanner**
#### Refactor ci_gen_kustomize_values

This role has to support more than the "simple" ctlplane configMap. In
order to do so, a deep refactoring has to be done.

From now on, the role is able to rewrite any configMap matching a known
"metadata.name".

#### Remove the snippet generator from networking_mapper role

This snippet is now properly generated from ci_gen_kustomize_values
role.

#### Update reproducer role to match new generator arch

Since ci_gen_kustomize_values is now handling "slightly" more
generations, we have to update the reproducer role to match the new
needs.

In order to avoid issues with `delegate_to`, facts and related
registered results, we now run most of the generation as a nested
playbook, launched directly via `ansible.builtin.command`. This ensures
we have the right context, and access to all of the needed parts.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role

### CODE REVIEW

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
Generated `edpm-values.yaml` with a 3-compute layout:
```YAML
data:
    nodes:
        edpm-compute-0:
            ansible:
                host: 192.168.122.100
            hostName: compute-0
            networks:
            -   defaultRoute: true
                fixedIP: 192.168.122.100
                name: ctlplane
                subnetName: subnet1
            -   name: internalapi
                subnetName: subnet1
            -   name: storage
                subnetName: subnet1
            -   name: tenant
                subnetName: subnet1
        edpm-compute-1:
            ansible:
                host: 192.168.122.101
            hostName: compute-1
            networks:
            -   defaultRoute: true
                fixedIP: 192.168.122.101
                name: ctlplane
                subnetName: subnet1
            -   name: internalapi
                subnetName: subnet1
            -   name: storage
                subnetName: subnet1
            -   name: tenant
                subnetName: subnet1
        edpm-compute-2:
            ansible:
                host: 192.168.122.102
            hostName: compute-2
            networks:
            -   defaultRoute: true
                fixedIP: 192.168.122.102
                name: ctlplane
                subnetName: subnet1
            -   name: internalapi
                subnetName: subnet1
            -   name: storage
                subnetName: subnet1
            -   name: tenant
                subnetName: subnet1
```
And if we get only 1 compute, it will reduce the list accordingly.

Generated `network-values.yaml` with a 3-node OCP cluster:
```YAML
    node_0:
        ctlplane_ip: 192.168.122.10
        internalapi_ip: 172.17.0.10
        name: master-0
        storage_ip: 172.18.0.10
        tenant_ip: 172.19.0.10
    node_1:
        ctlplane_ip: 192.168.122.11
        internalapi_ip: 172.17.0.11
        name: master-1
        storage_ip: 172.18.0.11
        tenant_ip: 172.19.0.11
    node_2:
        ctlplane_ip: 192.168.122.12
        internalapi_ip: 172.17.0.12
        name: master-2
        storage_ip: 172.18.0.12
        tenant_ip: 172.19.0.12
```
Here as well, with only CRC the list will be reduced to `node_0` and the `name` will match the one of the CRC node.

Seems things are mostly correct.

**Comment by cjeanner** [comment]
/hold cancel

In order to test this, you have to provide yet another extra-var file to the reproducer run, for instance `custom/code.yml`:
```YAML
---
local_home_dir: "{{ lookup('env', 'HOME') }}"
local_base_dir: "{{ local_home_dir }}/src/github.com/openstack-k8s-operators"
remote_base_dir: "/home/zuul/src/github.com/openstack-k8s-operators"
cifmw_reproducer_repositories:
  - src: "{{ local_base_dir }}/ci-framework"
    dest: "{{ remote_base_dir }}/"
```
Of course, update the `src` bit accordingly - `dest` is fine as-is. It will ensure you're pushing the correct code on the controller-0.

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
/hold

need to uncomment a play inclusion

**Comment by cjeanner** [comment]
/hold cancel

un-commented the 01-boostrap.yml inclusion, it's good to go now.

**Comment by fultonj** [comment]
The CRs genereated in network-values and edpm-values look OK, but have some content issues. Maybe we can try to address them first?

EDPM
```
[zuul@controller-0 edpm]$ kustomize build .
Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/home/zuul/architecture/va/nfv/sriov/edpm': accumulating components: accumulateDirectory: \"recursed accumulation of path '/home/zuul/architecture/lib/dataplane': fieldPath `data.nodeset.nodes` is missing for replacement source ConfigMap.[noVer].[noGrp]/edpm-values.[noNs]\""
[zuul@controller-0 edpm]$ 
```
I'm less concerned about the above since no one is relying on the EDPM CRs yet. But if people are actively using the control plane values which were generated from https://github.com/openstack-k8s-operators/ci-framework/pull/1025 then we might want to wait. Let me see if I can spot the error so we can at least get the network-values correct.

**Comment by cjeanner** [comment]
> The CRs genereated in network-values and edpm-values look OK, but have some content issues. Maybe we can try to address them first?
> 
> EDPM
> 
> ```
> [zuul@controller-0 edpm]$ kustomize build .
> Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/home/zuul/architecture/va/nfv/sriov/edpm': accumulating components: accumulateDirectory: \"recursed accumulation of path '/home/zuul/architecture/lib/dataplane': fieldPath `data.nodeset.nodes` is missing for replacement source ConfigMap.[noVer].[noGrp]/edpm-values.[noNs]\""
> [zuul@controller-0 edpm]$ 
> ```
> 
> I'm less concerned about the above since no one is relying on the EDPM CRs yet. But if people are actively using the control plane values which were generated from #1025 then we might want to wait. Let me see if I can spot the error so we can at least get the network-values correct.

@fultonj I think I have it - there was an issue with the indentation of the "nodes" block - it's supposed to be under `data.nodeset` while I had it under `data`, meaning at the same level as `nodeset` and `ssh_keys`... If you re-generate the content using the latest iteration of this PR, you should be all good!

**Comment by cjeanner** [comment]
/hold

there's apparently still an issue with network-values.yaml. Let's get it straight before merging.

**Comment by fultonj** [comment]
> /hold
> 
> there's apparently still an issue with network-values.yaml. Let's get it straight before merging.

The network-values.yaml issue that I encountered was from my environment and not this patch. I fixed my env and then I had no issue applying the control-plane CRs.

**Comment by fultonj** [comment]
> But if people are actively using the control plane values which were generated from #1025 then we might want to wait. Let me see if I can spot the error so we can at least get the network-values correct.

OK, I'm not concerned about this anymore. It was an issue in my env. 

I'll do more testing now with the edpm values.

**Comment by cjeanner** [comment]
/unhold
everything seems good now 🍾

**Comment by fultonj** [comment]
> > But if people are actively using the control plane values which were generated from #1025 then we might want to wait. Let me see if I can spot the error so we can at least get the network-values correct.
> 
> OK, I'm not concerned about this anymore. It was an issue in my env.
> 
> I'll do more testing now with the edpm values.

The issue I observed with edpm-values.yaml was resolved by [1].
In particular, `nodes` just needed to be indented under `nodeset`.
I'm +2 to merge

[1] https://github.com/openstack-k8s-operators/ci-framework/compare/20c293bad8724e21f103e3b79e7a41e2707d018d..d1f1541436185c29d9f530edc1242ddee484c9e9

**Pull request merged**
