### PR TITLE
Pin Ceph container to latest-reef

### PR DESCRIPTION
**Pull request by fmount**
Reef has been released recently [1] and the upstream development is going to see focus on the next "S" cycle. In order to avoid unexpected behaviors, the idea is to pin the Ceph container version to the latest Reef tag: this allow us to track regressions with the latest generated content and stay on track with the target release for Antelope OpenStack containers.

[1] https://ceph.io/en/news/blog/2023/v18-2-0-reef-released/

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
- [x] README in the role
- [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by pablintino** [comment]
recheck

**Comment by viroel** [comment]
/lgtm

still not using these roles in any job, but it will be tested against HCI job soon - thanks

**Comment by viroel** [comment]
recheck

**Review by raukadah — APPROVED** [review]
/approve

**Pull request merged**
