### PR TITLE
Reduce the controller nodeset

### PR DESCRIPTION
**Pull request by cjeanner**
Since we're not doing much on the controller, we can reduce its
footprint.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
https://review.rdoproject.org/r/c/config/+/50968 needs to be merged before recheck.

**Comment by cjeanner** [comment]
recheck

**Pull request merged**
