### PR TITLE
Allow to NOT have molecule job for selected role

### PR DESCRIPTION
**Pull request by cjeanner**
With this patch, we may avoid creating a useless molecule job and,
therefore, consuming resources for nothing.

If a new role is created, and the "molecule" directory is removed from
it, the script will not generate the molecule job for the new role.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running
- [X] Appropriate documentation exists and/or is up-to-date:
  - [X] README in the role
  - [X] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Review by marios — APPROVED** [review]
sounds good thanks

**Comment by cjeanner** [comment]
recheck

**Review by raukadah — APPROVED** [review]

**Comment by frenzyfriday** [comment]
recheck

**Pull request merged**
