### PR TITLE
Expose new parameter expectedFailuresList

### PR DESCRIPTION
**Pull request by kstrenkova**
This change is needed for the introduction of new parameter expectedFailuresList to the test operator. The parameter will be used for ignoring results of specified tests that are expected to fail.

### CODE REVIEW

**Review by lpiwowar — CHANGES_REQUESTED** [review]
Looks good to me:) :+1: . Please, update the [README.md](https://github.com/openstack-k8s-operators/ci-framework/blob/main/roles/test_operator/README.md) so that it describes the newly added parameter.

**Comment by kstrenkova** [comment]
> Looks good to me:) 👍 . Please, update the [README.md](https://github.com/openstack-k8s-operators/ci-framework/blob/main/roles/test_operator/README.md) so that it describes the newly added parameter.

I have added the changes to README.md :smile:

**Review by lpiwowar — APPROVED** [review]
Looks good to me! Thank you @kstrenkova :tada:

**Comment by lpiwowar** [comment]
recheck

**Comment by lpiwowar** [comment]
recheck

**Comment by lpiwowar** [comment]
@kstrenkova, please :pray: remove the merge commits and make sure that there is only one commit in this PR.

**Pull request closed without merging**
