### PR TITLE
Import compute hook update in dev-preview2

### PR DESCRIPTION
**Pull request by cjeanner**
As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by son-vyas** [comment]
testing here: https://review.rdoproject.org/r/c/testproject/+/40101

**Comment by son-vyas** [comment]
/lgtm

testing here:- https://review.rdoproject.org/zuul/stream/1b4b8d7bb0344f68952054fa328b1d0f?logfile=console.log

LOOP [Ensure we know compute host keys]
2023-11-01 11:27:45.672967 | controller | changed
2023-11-01 11:27:45.998418 | controller | changed

**Comment by pablintino** [comment]
@cjeanner @viroel I'm pretty sure we need this one here https://github.com/openstack-k8s-operators/ci-framework/pull/642 an this one on top of the other one https://github.com/openstack-k8s-operators/ci-framework/pull/650

**Comment by cjeanner** [comment]
@pablintino hmmm right - though the ssh-keyscan is already in, since I "copy-pasted" the file content. There were far, far too many conflicts with cherry-picks, and far, far too many patches altogether. Call me lazy if you wish..
I've nudged the inventory in the PR, we'll see. "just" to conflicts, should be mostly sorted out.

**Pull request merged**
