### PR TITLE
Add motd on controller-0

### PR DESCRIPTION
**Pull request by cjeanner**
This should provide some usefull environment information whenever a user
connects to the controller-0.

### CODE REVIEW

**Review by hjensas — COMMENTED** [review]
/lgtm

**Comment by raukadah** [comment]
It looks great!
```
[zuul@ospci-baremetal-01 ~]$ ssh controller-0
Warning: Permanently added 'controller-0.utility' (ED25519) to the list of known hosts.
Zuul job: ci-framework-baremetal-static-node-rhel9-va-hci
Change URL: https://review.rdoproject.org/r/c/tripleo-downstream-trigger-nested-virt/+/54276

Custom repositories:

Default repositories (might get overridden by above list):
https://github.com/openstack-k8s-operators/ci-framework in /home/zuul/src/github.com/openstack-k8s-operators/ci-framework at HEAD
https://github.com/openstack-k8s-operators/install_yamls in /home/zuul/src/github.com/openstack-k8s-operators/install_yamls at HEAD
https://github.com/openstack-k8s-operators/architecture in /home/zuul/src/github.com/openstack-k8s-operators/architecture at HEAD
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Wed Sep  4 22:12:10 2024 from 192.168.122.1
[zuul@controller-0 ~]$ 

```

**Pull request merged**
