### PR TITLE
[ceph] Ensure 1st monitor net facts are updated

### PR DESCRIPTION
**Pull request by pablintino**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by fmount** [comment]
@pablintino is this connected to [OSPRH-5638](https://issues.redhat.com/browse/OSPRH-5638)? It has been reported multiple times that zuul jobs fail due to the missing `ANSIBLE_GATHERING=implicit` (not sure it's missing but the fact that such variable is not honored could be the root cause of:

```bash
2024-03-15 05:49:02,736 p=28694 u=zuul n=ansible | TASK [Set IP address of first monitor cifmw_cephadm_first_mon_ip={{ hostvars[this_host][all_addresses] | ansible.utils.ipaddr(cifmw_cephadm_rgw_network) | first }}] ***
2024-03-15 05:49:02,737 p=28694 u=zuul n=ansible | Friday 15 March 2024  05:49:02 -0400 (0:00:00.089)       0:00:33.810 ********** 
2024-03-15 05:49:02,949 p=28694 u=zuul n=ansible | fatal: [compute-0]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: No first item, sequence was empty.. No first item, sequence was empty.\n\nThe error appears to be in '/home/zuul/src/github.com/openstack-k8s-operators/ci-framework/playbooks/ceph.yml': line 220, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set IP address of first monitor\n      ^ here\n"}
```

I'm +2 for this change, especially if it solves the above error just refreshing the facts when the `Ceph` playbook is run.

**Review by fultonj — COMMENTED** [review]
This looks like it solves the following:

  https://issues.redhat.com/browse/OSPRH-5638

+2

**Review by fmount — APPROVED** [review]
/lgtm

**Comment by cjeanner** [comment]
/approve

ansible fact caching are a pain sometimes :)

**Pull request merged**
