### PR TITLE
Update Kuttl and Molecule zuul jobs to CRC 2.39 - OCP 4.16

### PR DESCRIPTION
**Pull request by lewisdenny**
Jira: https://issues.redhat.com/browse/OSPRH-8665

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by lewisdenny** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by lewisdenny** [comment]
recheck

**Comment by raukadah** [comment]
Failing jobs passed in previous runs

cifmw-molecule-openshift_setup passed in https://github.com/openstack-k8s-operators/ci-framework/pull/2097#issuecomment-2231461023
cifmw-molecule-ci_nmstate passed in https://github.com/openstack-k8s-operators/ci-framework/pull/2097#issuecomment-2230105631
cifmw-multinode-kuttl passed in https://github.com/openstack-k8s-operators/ci-framework/pull/2097#issuecomment-2230497992

Going to override rdoproject.org/github-check

**Pull request merged**
