### PR TITLE
[Tobiko] Introduce Tobiko Workflows

### PR DESCRIPTION
**Pull request by lpiwowar**
This patch enables to specify Tobiko workflow for the test-operator role. This patch uses the newly introduced workflow section in the Tobiko CR that can be used to specify several workflow steps. The steps are executed sequentially.

This change ensures that we can set the workflow value and that the role waits for the last job that executes the tobiko tests (by using the workflowStep label)

Depends-On: https://github.com/openstack-k8s-operators/test-operator/pull/54

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by kopecmartin** [comment]
we need this asap as the follow up of the depends on - https://github.com/openstack-k8s-operators/test-operator/pull/54

**Review by kopecmartin — APPROVED** [review]
lgtm

**Comment by kopecmartin** [comment]
recheck

**Review by eduolivares — APPROVED** [review]

**Review by kopecmartin — APPROVED** [review]
lgtm, we need this asap as the follow up of the depends on - https://github.com/openstack-k8s-operators/test-operator/pull/54

**Review by eduolivares — APPROVED** [review]

**Pull request merged**
