### PR TITLE
Add tempest cleanup opt

### PR DESCRIPTION
**Pull request by kopecmartin**
Allow users to enable tempest cleanup feature defined in the tempest image.

https://github.com/openstack-k8s-operators/tcib/pull/208
https://github.com/openstack-k8s-operators/test-operator/pull/207

### CODE REVIEW

**Review by lpiwowar — APPROVED** [review]
Looks good to me! :+1:

**Comment by lewisdenny** [comment]
Hi @kopecmartin 

This change is fine foe me, do you have a test run passing that enables this feature? I note it's disabled by default but it would be nice to see a run passing with it enabled.

**Comment by lpiwowar** [comment]
Testing here -> https://github.com/openstack-k8s-operators/test-operator/pull/216

**Pull request merged**
