### PR TITLE
[ceph] Gather network facts for all computes

### PR DESCRIPTION
**Pull request by pablintino**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by cjeanner** [comment]
/approve

let's get all the facts :D (well, subset from all the nodes ;) )

**Review by fultonj — APPROVED** [review]
+2

**Review by rebtoor — APPROVED** [review]

**Review by raukadah — APPROVED** [review]

**Review by fmount — APPROVED** [review]
/lgtm

**Review by psathyan — APPROVED** [review]

**Comment by raukadah** [comment]
It fixes the issue. Now we are hitting a different issue.

**Pull request merged**
