### PR TITLE
Ensure CI playbooks have a name

### PR DESCRIPTION
**Pull request by cjeanner**
Using the play path as a name allows an easy understanding in case of
issues, since we can easily find what play failed.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by cjeanner** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Review by raukadah — COMMENTED** [review]
/approve

**Comment by raukadah** [comment]
recheck

**Comment by cjeanner** [comment]
Both failures are unrelated to the current patch... Not sure re-running endlessly will improve the results :/.

Still, the kuttl one is failing on keystone on a steady trend, maybe there's something in there, but unrelated to this patch...

Getting those playbook names will improve readability and understanding of the logs, providing a good overview of what play is failing for instance, making the whole debugging thing easier.

Shall we discard those 2 failures and force this one in the tree?

**Pull request merged**
