### PR TITLE
Udpate openstack_containers in periodic lines

### PR DESCRIPTION
**Pull request by raukadah**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/319

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by rlandy** [comment]
https://review.rdoproject.org/zuul/buildset/229ead8205de437e88fdeaa35b0fd22e testproject results ...https://logserver.rdoproject.org/59/45359/37/check/periodic-podified-edpm-deployment-ante[…]/ci-framework-data/artifacts/update_containers_patch.out shows e1ee122c409bcbb83bc782fb7abbae37 which is https://trunk.rdoproject.org/centos9-antelope/podified-ci-testing/delorean.repo.md5

**Review by rlandy — COMMENTED** [review]
/lgtm

**Comment by viroel** [comment]
Thanks @raukadah lgtm

**Pull request merged**
