### PR TITLE
Use a bigger flavor for standalone node in adoption

### PR DESCRIPTION
**Pull request by cescgina**
The standalone deployment seems to fail with what seems to be
resource-related conditions, so trying to use a biggere flavor there
with more RAM.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by lewisdenny** [comment]
recheck failed on: `wait for dataplane node set to be ready`

**Review by marios — APPROVED** [review]
yes lets

currently 8gb vm is not enough, especially if we are expecting to launch nested vms on that

**Comment by marios** [comment]
recheck

**Comment by marios** [comment]
as discussed in call now with Ronelle and Joan we are going to force merge this one.

it just touches the label for the adoption job so we feel it is safe to merge and should help with our ongoing cix

**Pull request merged**
