### PR TITLE
Feature/libvirt manager role

### PR DESCRIPTION
**Pull request by cjeanner**
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/201

This PR has:
- [x] Appropriate testing (molecule, python unit tests)
- [x] Appropriate documentation (README in the role, main README is up-to-date)

### CODE REVIEW

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
/test ansible-test pre-commit

We have to wait for https://github.com/openstack-k8s-operators/install_yamls/pull/201 to merge (the other one was needed for debugging purpose). And then, this one seems ready to merge!

**Review by raukadah — APPROVED** [review]
Looks good, not able find any issues. Let's merge it.

**Pull request merged**
