### PR TITLE
Update edpm, multinode and e2e to crc 2.36(OCP 4.15)

### PR DESCRIPTION
**Pull request by lewisdenny**
Jira: https://issues.redhat.com//browse/OSPRH-6868

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by lewisdenny** [comment]
Error: `curl -sL https://github.com/openstack-k8s-operators/repo-setup/archive/refs/heads/main.tar.gz\n\ngzip: stdin: unexpected end of file\ntar: Child returned status 1\ntar: Error is not recoverable: exiting now"`

Local:
```
$ curl -sL https://github.com/openstack-k8s-operators/repo-setup/archive/refs/heads/main.tar.gz | tar -xz
$ echo $?
0
```
File seems fine to me so maybe recheck will help

**Comment by lewisdenny** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Comment by lewisdenny** [comment]
recheck

**Comment by pablintino** [comment]
@lewisdenny I leave a hold to avoid shipping this on Friday, remove it when you start on Monday :)

**Pull request merged**
