### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by IgnacioPro**
Requesting review access

### CODE REVIEW

**Comment by cjeanner** [comment]
/lgtm

Provided you have your access in the openshift orga, I think it will be required shortly.

**Comment by IgnacioPro** [comment]
> /lgtm
> 
> Provided you have your access in the openshift orga, I think it will be required shortly.

I do yes.

**Comment by cjeanner** [comment]
recheck

**Review by cjeanner — APPROVED** [review]

**Pull request merged**
