### PR TITLE
Remove multi-hypervisor testing in molecule

### PR DESCRIPTION
**Pull request by cjeanner**
This feature will make IPv6 support addition far too complicated for
now, and since it's apparently not used nor really advertised, let's
"just" stop testing it.

Reverting the whole feature would be too complicated as well - and
we might want to get it back in the future.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is removed

### CODE REVIEW

**Review by lewisdenny — CHANGES_REQUESTED** [review]
Patch looks good, before merging it would be good to update these two (any any others you know of) saying this feature isn't tested/supported:
- https://ci-framework.readthedocs.io/en/latest/quickstart/02_prepare_env.html#multiple-hypervisor
- https://ci-framework.readthedocs.io/en/latest/quickstart/03_deploy_infra.html#multi-hypervisor-case

**Comment by cjeanner** [comment]
@lewisdenny there's also an open MR in downstream doc.

**Review by lewisdenny — APPROVED** [review]
/lgtm

**Review by rlandy — COMMENTED** [review]
/lgtm

**Pull request merged**
