### PR TITLE
edpm_kustomize hack that allows multidocument manifests

### PR DESCRIPTION
**Pull request by pablintino**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date

### CODE REVIEW

**Comment by pablintino** [comment]
recheck

**Comment by viroel** [comment]
results looks good:
Current deployments working: https://logserver.rdoproject.org/53/553/25e2b852fdfef0c6813ceea9a92ee01fc4473dc2/github-check/podified-multinode-edpm-deployment-crc/7b86029/controller/ci-framework-data/artifacts/manifests/openstack/dataplane/cr/

And for DataPlaneDeploymentCRD (not yet merged)
https://logserver.rdoproject.org/78/378/d517a31a80c32608d107ef6f9569abe8b0ce1877/github-check/podified-multinode-edpm-deployment-crc/812825b/controller/ci-framework-data/artifacts/manifests/openstack/dataplane/cr/

**Comment by viroel** [comment]
/lgtm

lets get this in

**Pull request merged**
