### PR TITLE
Remove molecule dir from sw role

### PR DESCRIPTION
**Pull request by eshulman2**
As requested for this module I'm removeing the molecule dir, there is no way to run molecule tests for this module in this project CI.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Review by dpinhas — COMMENTED** [review]
To avoid running cifmw-molecule-switch_config in zuul, you should remove the referenced jobs from 
- zuul.d/projects.yaml#55
- zuul.d/molecule.yaml#462-471

**Review by cjeanner — CHANGES_REQUESTED** [review]
@eshulman2 care to run `make role_molecule` once you removed the directory from the role? It will re-generate the projects.yaml + molecule.yaml files in the zuul.d directory.

**Comment by eshulman2** [comment]
thanks @cjeanner and @dpinhas updated

**Pull request merged**
