### PR TITLE
[networking_mapping] Make hostvars optional for partial maps

### PR DESCRIPTION
**Pull request by pablintino**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1011

### CODE REVIEW

**Comment by raukadah** [comment]
tox -e black will fix the pre-commit and tox prow jobs.

**Comment by pablintino** [comment]
> tox -e black will fix the pre-commit and tox prow jobs.

@raukadah done!

**Review by cjeanner — APPROVED** [review]
/approve

**Pull request merged**
