### PR TITLE
[copy-quay] Don't push tag if hash already exists on dest namespace

### PR DESCRIPTION
**Pull request by michaeltcoelho**
@pablintino As requested, I've removed the code formatting changes for this PR.

As a pull request owner and reviewers, I checked that:

- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by arxcruz** [comment]
lgtm

**Comment by arxcruz** [comment]
/lgtm
lgtm
I never know which one to use

**Comment by cjeanner** [comment]
/approve

looks sane to me. Better handling of existing tags in case of re-run, better logging handler - looks fine.

**Pull request merged**
