### PR TITLE
Interactively create VM on openstack cloud

### PR DESCRIPTION
**Pull request by dsariel**
This PR has:
- [ ] Appropriate testing (molecule, python unit tests)
- [ ] Appropriate documentation (README in the role, main README is up-to-date)

### CODE REVIEW

**Review by cjeanner — COMMENTED** [review]
This is something we probably want integrated in the 01-infra.yml playbook... Therefore, would it be possible to get that as ansible?
Basically:
- getting the VM (maybe using the openstack ansible module, though... it may lag compared to the actual API, probably better to get it as shell/command)
- parsing the outputs (you can format them as json, so it's easy to do in ansible)
- injecting the node in the inventory

Doing so, we'd be able to use that same unique entry point, while converging technologies..

Also: please, ensure you're up-to-date against `main` when submitting PR, things are moving fast, and you may be missing some of the latest corrections in your local code.

**Comment by dsariel** [comment]
> This is something we probably want integrated in the 01-infra.yml playbook... Therefore, would it be possible to get that as ansible? Basically:
> 
> * getting the VM (maybe using the openstack ansible module, though... it may lag compared to the actual API, probably better to get it as shell/command)
> * parsing the outputs (you can format them as json, so it's easy to do in ansible)
> * injecting the node in the inventory
> 
> Doing so, we'd be able to use that same unique entry point, while converging technologies..
> 
> Also: please, ensure you're up-to-date against `main` when submitting PR, things are moving fast, and you may be missing some of the latest corrections in your local code.
> 
> EDIT: if you want to get user inputs within ansible, there's https://docs.ansible.com/ansible/2.9/user_guide/playbooks_prompts.html available :)

Thanks for the feedback. I'll take a look at ./ci_framework/playbooks/01-bootstrap.yml (guess that was your intention mentioning 01-infra.yml)

**Comment by dsariel** [comment]
> up-to-date against `main` when submitting PR, things are moving fast, and you may be missing some of the latest corrections in your local code.

I have rebased on top of main this afternoon (in vain), but will try again now. Thanks!

**Comment by pablintino** [comment]
Hi @dsariel , this is stale for so long, what's the actual status of this PR?

**Comment by cjeanner** [comment]
PR is stalled - closing. Feel free to re-open it with an update if needed.
Note that we're getting out of the "nested virt" scenario - and someone should be working on porting that non-nested on standard openstack ("standard" compared to CI).

**Pull request closed without merging**
