### PR TITLE
DNM Checking CRC 2.39 base on OCP 4.16

### PR DESCRIPTION
**Pull request by danpawlik**

### CODE REVIEW

**Comment by cescgina** [comment]
recheck

**Comment by cescgina** [comment]
recheck

**Comment by cescgina** [comment]
recheck

**Comment by cescgina** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
Almost green \o/ . One job fails because of the k1s host.

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by pablintino** [comment]
@danpawlik is this test PR still needed?

**Comment by pablintino** [comment]
Stale PR, closing. Feel free to reopen it if needed.

**Pull request closed without merging**
