### PR TITLE
Inject a README file in generated logs

### PR DESCRIPTION
**Pull request by cjeanner**
This should help users getting straight to the logs.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by cjeanner** [comment]
recheck

**Comment by cjeanner** [comment]
https://logserver.rdoproject.org/36/336/5d25a1c6b725b1e1e84000d61056c9052bb520a3/github-check/cifmw-end-to-end-nobuild-tagged/21f03f3/

looks nice - @Sandeepyadav93 any thoughts? @kajinamit would this help you navigating the logs?

**Comment by Sandeepyadav93** [comment]
/lgtm

This looks fantastic.

**Pull request merged**
