### PR TITLE
Move all the base jobs to base.yaml

### PR DESCRIPTION
**Pull request by raukadah**
Moving all the base jobs to a single file allow us to use anchors. Here irrelevant files always causes job freeze issue.

Keeping base-jobs at one place allow us to manage irrelevant files easily.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by raukadah** [comment]
recheck

**Review by cjeanner — APPROVED** [review]
/approve

Nice to see anchor in place thanks to that patch

**Comment by cjeanner** [comment]
/lgtm cancel

missing the edpm_multinode base job

**Pull request merged**
