### PR TITLE
Retry getting k8s resource

### PR DESCRIPTION
**Pull request by afazekas**
Looks like some cases the requested resource
is not provided at this point of time.

`better say sorry than ask for permission` retry
strategy put here until better solution
comes.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by afazekas** [comment]
recheck

**Review by gibizer — COMMENTED** [review]
The workaround looks good to me.

**Review by raukadah — APPROVED** [review]

**Pull request merged**
