### PR TITLE
Add missing node groups for multicell nodeset

### PR DESCRIPTION
**Pull request by bogdando**
JIRA [OSPRH-6548](https://issues.redhat.com/browse/OSPRH-6548)

Required-By: https://github.com/openstack-k8s-operators/data-plane-adoption/pull/517

### CODE REVIEW

**Review by marios — APPROVED** [review]

**Comment by bogdando** [comment]
I don't get that error, any help please?

**Comment by bogdando** [comment]
recheck

**Comment by fserucas** [comment]
recheck

**Comment by fserucas** [comment]
recheck

**Comment by bogdando** [comment]
please merge this

**Comment by cescgina** [comment]
recheck

**Comment by bogdando** [comment]
good to go now

**Review by lewisdenny — APPROVED** [review]
/approve

**Review by jistr — APPROVED** [review]

**Pull request merged**
