### PR TITLE
scenarios/centos9/multinode-ci: set install_yamls/BMO_SETUP=false by default

### PR DESCRIPTION
**Pull request by elfiesmelfie**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
My jobs have failed a few times, and  think it's a good efficiency to skip setting up the baremetal operator if it isn't generally used in the multinode jobs. If nothing else, it'll reduce the number of rechecks needed, and reduce a bit of load on the CI

Most recent failure:
https://github.com/openstack-k8s-operators/telemetry-operator/pull/301#issuecomment-1946924985

**Comment by elfiesmelfie** [comment]
@cescgina My Job appear to still be failing on the same issue as above. The baremetal-operator-controller is crashlooping.
The `BMO_SETUP: false` seems to be set though, so it seems to me that there are more steps to diable the baremetal operator

**Comment by pablintino** [comment]
@elfiesmelfie @cescgina looks good to me, but I'll approve it only if a run of the baremetal job ensures it's green. Feel free to test is using a tesproject change.

**Comment by elfiesmelfie** [comment]
> @elfiesmelfie @cescgina looks good to me, but I'll approve it only if a run of the baremetal job ensures it's green. Feel free to test is using a tesproject change.

What action do I need to take for the bare metal job to run on this change?

**Comment by cescgina** [comment]
> > @elfiesmelfie @cescgina looks good to me, but I'll approve it only if a run of the baremetal job ensures it's green. Feel free to test is using a tesproject change.
> 
> What action do I need to take for the bare metal job to run on this change?

@elfiesmelfie @pablintino I believe making a small change (like a comment) on https://github.com/openstack-k8s-operators/ci-framework/blob/main/ci/playbooks/edpm_baremetal_deployment/run.yml should trigger the baremetal job, and after we have a green run we can remove the small change

**Comment by cescgina** [comment]
@elfiesmelfie even simpler, I'm running it in a testproject here https://review.rdoproject.org/r/c/testproject/+/51764

**Comment by cescgina** [comment]
> @elfiesmelfie @cescgina looks good to me, but I'll approve it only if a run of the baremetal job ensures it's green. Feel free to test is using a tesproject change.

@pablintino baremetal job passed in https://review.rdoproject.org/r/c/testproject/+/51764

**Pull request merged**
