### PR TITLE
Add barbican and swift operators to required-projects list

### PR DESCRIPTION
**Pull request by dasm**
Depends-On: https://review.rdoproject.org/r/c/config/+/49768

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by dasm** [comment]
@raukadah based on your comment: https://review.rdoproject.org/r/c/config/+/49761/1#message-ed9716a5ce680e2d6d8c753fb22f4bcfe3da0867

**Comment by raukadah** [comment]
recheck

**Pull request merged**
