### PR TITLE
Drop unused dataplane vars

### PR DESCRIPTION
**Pull request by fao89**
ref:
- https://github.com/openstack-k8s-operators/install_yamls/pull/810
- https://github.com/openstack-k8s-operators/openstack-operator/pull/765

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by pablintino** [comment]
@fao89 Hi! just a hint: The values touched here are only mock data used to test that the install_yamls logic we have to parse the Makefile defaults works, so those ones are not used to deploy and there is no strict need to make them match the content of main in install_yamls. If for the sake of consistency you want to patch them to match I'm ok with it, but I'd not loose too much time trying to get this patch to work.

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
@rebtoor could you please take a look?

**Review by rebtoor — APPROVED** [review]

**Pull request merged**
