### PR TITLE
Convert -nobuild job to -tagged-nobuild

### PR DESCRIPTION
**Pull request by cjeanner**
This job goal is to ensure tags are covering the needs accordingly.

Running the deploy-edpm.yml playbook three times with a combination of
`--tags` and `--skip-tags` should ensure we're delivering the needed
feature.

Note that, as we get more and more tags, we may need to revisit this
base job.

Since it's a 100% overlap with the "-nobuild" job, we just convert that
one, saving resources.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by cjeanner** [comment]
issue isn't related to the tags, but to, apparently, crc resource outage...

**Comment by cjeanner** [comment]
recheck

**Review by raukadah — APPROVED** [review]
Checked the logs, tags are working properly.

**Comment by raukadah** [comment]
@cjeanner Below is the playbook run from packages tag.
```
libvirt_manager : Install packages required for using KVM -------------- 12.17s
2023-06-06 11:54:57.324058 | controller | repo_setup : Initialize python venv and install requirements ------------ 5.22s
2023-06-06 11:54:57.324066 | controller | repo_setup : Get repo-setup repository ---------------------------------- 1.24s
2023-06-06 11:54:57.324073 | controller | Gathering Facts --------------------------------------------------------- 1.08s
2023-06-06 11:54:57.324081 | controller | ci_setup : Manage directories ------------------------------------------- 1.02s
2023-06-06 11:54:57.324089 | controller | ci_setup : Install needed packages -------------------------------------- 0.90s
2023-06-06 11:54:57.324097 | controller | repo_setup : Run repo-setup --------------------------------------------- 0.90s
2023-06-06 11:54:57.324106 | controller | repo_setup : Install repo-setup package --------------------------------- 0.74s
2023-06-06 11:54:57.324114 | controller | repo_setup : Dump full hash in delorean.repo.md5 file ------------------- 0.72s
2023-06-06 11:54:57.324121 | controller | Create artifacts with custom params ------------------------------------- 0.55s
2023-06-06 11:54:57.324129 | controller | rhol_crc : Ensure directories exist ------------------------------------- 0.51s
2023-06-06 11:54:57.324137 | controller | install_yamls : Ensure directories exist -------------------------------- 0.50s
2023-06-06 11:54:57.324145 | controller | pkg_build : Ensure per-package log directories exist -------------------- 0.50s
2023-06-06 11:54:57.324153 | controller | repo_setup : Ensure directories are present ----------------------------- 0.48s
2023-06-06 11:54:57.324174 | controller | repo_setup : Run repo-setup=get-hash ------------------------------------ 0.47s
2023-06-06 11:54:57.324182 | controller | install_ca : Ensure target directory exists ----------------------------- 0.42s
2023-06-06 11:54:57.324190 | controller | ci_setup : Gather version of openshift client if it exists -------------- 0.34s
2023-06-06 11:54:57.324197 | controller | libvirt_manager : Ensure output directory exists ------------------------ 0.26s
2023-06-06 11:54:57.324205 | controller | edpm_prepare : Set install_yamls Makefile environment variables --------- 0.21s
2023-06-06 11:54:57.324213 | controller | operator_build : Initialize role output --------------------------------- 0
```
It also includes directories creation tasks. May be we can move them to bootstrap only and keep the `packages` tag to installation tasks only. What do you say?

**Comment by cjeanner** [comment]
> @cjeanner Below is the playbook run from packages tag.
> It also includes directories creation tasks. May be we can move them to bootstrap only and keep the `packages` tag to installation tasks only. What do you say?

IMHO `bootstrap` should include `packages` - and `packages` shouldn't include `bootstrap`. That means:
running `packages` should install packages only, running `bootstrap` should create directories and install packages.

Now, some `packages` tasks rely on the directories - there are therefore some tasks tagged as `always`. For instance, `repo_setup` relies on the availability of `{{cifmw_basedir}}/artifacts/` - sooo... it's "complicated".

Still - now that we have a proper CI job, we can tweak tags while ensuring things are still working, which is pretty cool :).

**Pull request merged**
