### PR TITLE
Remove Validated Architecture related content

### PR DESCRIPTION
**Pull request by cjeanner**
This is mosly a downstream resource, so let's keep the upstream content
simple and readable.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate documentation exists and/or is up-to-date:
  - [X] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by cjeanner** [comment]
/hold

we have to get the downstream doc built first.

**Review by raukadah — APPROVED** [review]

**Review by lewisdenny — APPROVED** [review]

**Pull request merged**
