### PR TITLE
Issue/osprh 6541

### PR DESCRIPTION
**Pull request by slawqo**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

Closes: [OSPRH-6541](https://issues.redhat.com//browse/OSPRH-6541)

### CODE REVIEW

**Review by SeanMooney — APPROVED** [review]
i was going to say this looks like its missing the default subnet pool based on https://docs.openstack.org/neutron/latest/admin/config-auto-allocation.html

but slaweq mentioned that has already been done in a separate pr and has been configured for some time.

given that this should be good as is

**Comment by slawqo** [comment]
recheck

**Comment by SeanMooney** [comment]
check-rdo

**Comment by SeanMooney** [comment]
ok its queded here https://review.rdoproject.org/zuul/status/change/1681,e8f8c61fd3ca922c728315b0aee857dc9f135ef9 so that should report back when doen

i think it got confused since we both rebased at the same time

**Comment by SeanMooney** [comment]
actully no https://review.rdoproject.org/zuul/buildset/2780c63a999c47edbf268d7ff0a89016 it did fail again... im really not sure why

**Comment by cjeanner** [comment]
recheck

**Pull request merged**
