### PR TITLE
Add the owner group in GroupTemplateDefinition

### PR DESCRIPTION
**Pull request by pablintino**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Review by rebtoor — APPROVED** [review]

**Comment by lewisdenny** [comment]
Maybe tide is messed up here because the tests were run on the cluster that was upgrading at the time 

```
cluster: build02
```

[00:20](https://redhat-internal.slack.com/archives/CFUGK0K9R/p1702304418636799)
:warning: build02 will be upgraded to 4.15.0-ec.3 today. [#openshift4-next-b02](https://redhat-internal.slack.com/archives/C03G7REB4JV)

**Comment by lewisdenny** [comment]
Actually I checked the prow config in the release repo and didn’t note any recent changes. The default is to allow `merge` but it can be blocked in github apparently but I don’t have any permission to check.

**Comment by lewisdenny** [comment]
recheck

**Comment by lewisdenny** [comment]
> Actually I checked the prow config in the release repo and didn’t note any recent changes. The default is to allow `merge` but it can be blocked in github apparently but I don’t have any permission to check.

Yes we needed this after a repo change: https://github.com/openshift/release/pull/46704

**Pull request merged**
