### PR TITLE
Disable tempest ca verification in scenarios

### PR DESCRIPTION
**Pull request by stuggi**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
from job logs we get the intended settings changed:
```
[identity]
...
disable_ssl_certificate_validation = True
v3_endpoint_type = publicURL
...
[dashboard]
disable_ssl_certificate_validation = True
```

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
recheck

**Comment by cjeanner** [comment]
@stuggi care to rebase against `main` ? #656 is in

**Review by cjeanner — COMMENTED** [review]
/approve

**Comment by stuggi** [comment]
```
2023-10-11 15:39:38.393 5 INFO config_tempest.constants [-] Downloading 'https://download.cirros-cloud.net/0.5.2/cirros-0.5.2-x86_64-disk.img' and saving as '/var/lib/tempest/openshift/etc/cirros-0.5.2-x86_64-disk.img'[00m
2023-10-11 15:41:48.995 5 WARNING config_tempest.constants [-] <urlopen error [Errno 101] Network is unreachable>, Retrying in 3 seconds.: urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>[00m
```

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
recheck

**Pull request merged**
