### PR TITLE
Removing jmespath

### PR DESCRIPTION
**Pull request by jpodivin**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by jpodivin** [comment]
recheck

**Comment by pablintino** [comment]
Hi! @jpodivin Can you please provide more context about why are we willing to remove `jsmespath`?

**Comment by jpodivin** [comment]
> Hi! @jpodivin Can you please provide more context about why are we willing to remove `jsmespath`?

Certainly. package isn't maintained and now it's no longer necessary. Therefore there is no need to keep it in reqs.

**Comment by jpodivin** [comment]
In retrospect I'm not 100% sure we need to do this in the ci-framework as well. Putting on hold until I know.

**Comment by cjeanner** [comment]
:-1: 
That library is needed for any |json_query filters. We can't remove it then.

**Pull request closed without merging**
