### PR TITLE
Add retries to install_yamls input target

### PR DESCRIPTION
**Pull request by viroel**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by pablintino** [comment]
recheck

**Comment by viroel** [comment]
recheck

**Review by raukadah — APPROVED** [review]
It is needed for downstream job

**Pull request merged**
