### PR TITLE
[install_yamls] Allow install_yamls env vars patches

### PR DESCRIPTION
**Pull request by pablintino**
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/937

### CODE REVIEW

**Comment by pablintino** [comment]
recheck

**Review by lewisdenny — CHANGES_REQUESTED** [review]
2 comments on this one:

Why can we not just use `cifmw_install_yamls_vars`? I see in #2453 you want to set `INSTALL_NMSTATE: false`

If we can not use `cifmw_install_yamls_vars` please add `cifmw_install_yamls_vars_patch_*` usage to the role README

**Comment by pablintino** [comment]
> 2 comments on this one:
> 
> Why can we not just use `cifmw_install_yamls_vars`? I see in #2453 you want to set `INSTALL_NMSTATE: false`
> 
> If we can not use `cifmw_install_yamls_vars` please add `cifmw_install_yamls_vars_patch_*` usage to the role README
Unfortunatly no, it's not that easy, as we are defining the base `cifmw_install_yamls_vars`  in many files https://github.com/search?q=repo%3Aopenstack-k8s-operators%2Fci-framework+path%3A%22scenarios%2F%22+cifmw_install_yamls_vars&type=code. We can create another one, but it will be just another copy, that's why I prefer to go this route.
README updated.

**Review by lewisdenny — APPROVED** [review]
/approve

**Comment by lewisdenny** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Review by lewisdenny — APPROVED** [review]
/approve

@bshewale @frenzyfriday Could you please check this one and lgtm? :)

**Comment by frenzyfriday** [comment]
/lgtm

the logic lgtm, and the molecule test confirms it

**Pull request merged**
