### PR TITLE
Fixing get_makefiles_env when special chars are in place

### PR DESCRIPTION
**Pull request by pablintino**
Some values may contain special chars like % that may affect the underneath printf command. By replacing printf with echo that is way more simple and doesn't format the input, something that is not needed here as it was only used to add line breaks, special chars should pass correctly without causing issues.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:

### CODE REVIEW

**Comment by cjeanner** [comment]
/approve

Makes sense. Also good to enable the `check` in the subprocess, in order to raise errors on due time. It should help debugging in the future.

**Comment by rabi** [comment]
This does not run the baremetal job, so should be tested with a depends-on patch in dataplane-operator or other repos.

**Review by raukadah — COMMENTED** [review]
+2 looks good.

**Comment by cjeanner** [comment]
/test pre-commit
Doesn't seem to be caused by the PR

**Comment by cjeanner** [comment]
/lgtm

Let's wait for the last pre-commit one, and manually merge. Zuul issue is unrelated.

**Comment by cjeanner** [comment]
Locally ran the pre-commit job, it passed. Prow seems to have an issue. Merging.

**Pull request merged**
