### PR TITLE
Moving to nodeset coreos-crc-extracted-3xl which has 12vcpus

### PR DESCRIPTION
**Pull request by frenzyfriday**
Nodeset is added here: https://softwarefactory-project.io/r/c/config/+/29784

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running
- [X] Appropriate documentation exists and/or is up-to-date:
  - [X] README in the role
  - [X] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by pablintino** [comment]
As I said internally, this flavor is not the expected one, that is `12vcpu_24GB`

**Comment by frenzyfriday** [comment]
recheck

**Comment by frenzyfriday** [comment]
Updated the nodeset to the correct flavor now

**Comment by frenzyfriday** [comment]
recheck

**Pull request merged**
