### PR TITLE
Remove old unused CRC nodesets

### PR DESCRIPTION
**Pull request by lewisdenny**
The 3 matches from `tripleo-ci-internal-jobs` are beta jobs that will soon be removed with `tripleo-ci-internal-jobs` closing down.

For the match in `weirdo-jobs.yaml`, I reached out to Joel and awaiting a response on if this is needed or they will bump to CRC 2.39:

```
❯ tree -L 2
.
├── downstream
│   ├── ci-framework-config
│   ├── ci-framework-jobs
│   ├── ci-framework-testproject
│   ├── docs
│   ├── sf-config
│   ├── testproject
│   ├── tripleo-ci-internal-config
│   └── tripleo-ci-internal-jobs
└── upstream
    ├── ci-bootstrap
    ├── ci-framework
    ├── ci-framework.worktrees
    ├── config
    ├── data-plane-adoption
    ├── rdo-jobs
    ├── release
    ├── review.rdoproject.org-config
    └── testproject

❯ rg -g '*.yaml' nodeset:.\*2-3 | rg -v '2-39'
upstream/rdo-jobs/zuul.d/weirdo-jobs.yaml:    nodeset: centos-9-crc-2-30-0-6xlarge
downstream/tripleo-ci-internal-jobs/zuul.d/podified-jobs.yaml:    nodeset: rhel-9-4-crc-extracted-2-30-0-3xl
downstream/tripleo-ci-internal-jobs/zuul.d/edpm.yaml:    nodeset: 2x-rhel-9-4-crc-extracted-2-30-0-xxl
downstream/tripleo-ci-internal-jobs/zuul.d/edpm.yaml:    nodeset: 2x-rhel-9-4-crc-extracted-2-30-0-3xl
```

Jira: [OSPRH-8666](https://issues.redhat.com//browse/OSPRH-8666)

Depends-On: https://review.rdoproject.org/r/c/config/+/53945

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by lewisdenny** [comment]
I need to update the nova-operator zuul config to not pull config from these renovate branches.

**Comment by lewisdenny** [comment]
recheck

**Comment by lewisdenny** [comment]
Just waiting on [1] to merge
[1] https://review.rdoproject.org/r/c/config/+/53945

**Comment by lewisdenny** [comment]
recheck

**Comment by lewisdenny** [comment]
recheck

**Comment by rlandy** [comment]
recheck

**Comment by rlandy** [comment]
recheck

**Review by raukadah — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
