### PR TITLE
[install_yamls] Skip setting operators_repo var for repos not in openstack-k8s-operators org

### PR DESCRIPTION
**Pull request by elfiesmelfie**
https://logserver.rdoproject.org/85/585/6d95d205438e4a2a78f43f4606ae2efd0a29c678/github-check/stf-crc-ocp_414-local_build-index_deploy/a646dd6/controller/ci-framework-data/logs/ansible.log-2024-04-04-10:47 2024-04-04 10:47:09,970 p=28890 u=zuul n=ansible | TASK [install_yamls : Get environment structure base_path={{ cifmw_install_yamls_repo }}] ***
2024-04-04 10:47:09,970 p=28890 u=zuul n=ansible | Thursday 04 April 2024  10:47:09 -0400 (0:00:00.036)       0:00:56.974 ********
2024-04-04 10:47:10,143 p=28890 u=zuul n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: line 1: SERVICE-TELEMETRY_REPO=/home/zuul/src/github.com/infrawatch/service-telemetry-operator: No such file or directory\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
@cjeanner This is an alternative to [1]

This one is probably less disruptive.

**Comment by lewisdenny** [comment]
> @cjeanner This is an alternative to [1]
> 
> This one is probably less disruptive.

I think you missed the link for [1]? If so, I do that all the time and it's super annoying! :D

**Review by lewisdenny — APPROVED** [review]
Nice clean solution, thanks for adding the test case!

```
2024-04-15 13:13:24.862712 | controller | TASK [Create variables with local repos based on Zuul items] *******************
2024-04-15 13:13:24.913265 | controller |
2024-04-15 13:13:24.913327 | controller | TASK [install_yamls : Create variables with local repos based on Zuul items] ***
2024-04-15 13:13:25.057517 | controller | skipping: [instance] => (item={'project': {'short_name': 'ci-framework', 'name': 'openstack-k8s-operators/ci-framework', 'src_dir': 'src/github.com/openstack-k8s-operators/ci-framework'}})
2024-04-15 13:13:25.057556 | controller | ok: [instance] => (item={'project': {'short_name': 'dataplane-operator', 'name': 'openstack-k8s-operators/dataplane-operator', 'src_dir': 'src/github.com/openstack-k8s-operators/dataplane-operator'}})
2024-04-15 13:13:25.057568 | controller | ok: [instance] => (item={'project': {'short_name': 'openstack-baremetal-operator', 'name': 'openstack-k8s-operators/openstack-baremetal-operator', 'src_dir': 'src/github.com/openstack-k8s-operators/openstack-baremetal-operator'}})
2024-04-15 13:13:25.057776 | controller | skipping: [instance] => (item={'project': {'short_name': 'service-telemetry-operator', 'name': 'infrawatch/service-telemetry-operator', 'src_dir': 'src/github.com/infrawatch/service-telemetry-operator'}})
```

**Comment by elfiesmelfie** [comment]
> > @cjeanner This is an alternative to [1]
> > This one is probably less disruptive.
> 
> I think you missed the link for [1]? If so, I do that all the time and it's super annoying! :D

Updated! I agree, super annoying!

**Comment by viroel** [comment]
/approve

thanks for this fix.
I agree that all repos will need to be operators from openstack-k8s-operators, otherwise we can skip.
We are only interested on repos clone in install_yamls makefile/scripts that are part of the meta operator.

**Pull request merged**
