### PR TITLE
Use default single-nic-vlans.j2

### PR DESCRIPTION
**Pull request by bshephar**
We have removed the bespoke API interface used to override nic-config files in favor or the direct Ansible variable. This change ensures that we don't remove the variable from the template, which is currently using the standard single-nic-vlans.j2 file:
https://github.com/openstack-k8s-operators/dataplane-operator/pull/394/files 
https://github.com/openstack-k8s-operators/edpm-ansible/pull/243

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by pablintino** [comment]
Uhmmm failed to apply the first networking config https://logserver.rdoproject.org/60/560/add973e5615e1274650ff306e019205226536103/github-check/podified-multinode-edpm-deployment-crc/9a818ed/controller/ci-framework-data/artifacts/must-gather.local.2949961155780841694/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-070a98749455b097c66a1a25ff827a3c0ee7385f1f0c8bf54f5b15438501f2bd/namespaces/openstack/pods/dataplane-deployment-configure-network-openstack-edpm-24wqc/logs/dataplane-deployment-configure-network-openstack-edpm-24wqc.log and after that the compute was unreachable (see the other logs from the other pods of the same job).

**Comment by pablintino** [comment]
recheck

**Comment by bshephar** [comment]
> Maybe using `Depends-On` may help testing things up?

I have the Depends-On for the dataplane-operator PR so that it Depends-On this PR:
https://github.com/openstack-k8s-operators/dataplane-operator/pull/394

Do you think it should be the other way around?

**Comment by bshephar** [comment]
recheck

**Comment by bshephar** [comment]
Ops, wrong PR to recheck. My bad.

**Pull request merged**
