### PR TITLE
Ignore computes deployment when cifmw_use_libvirt is false

### PR DESCRIPTION
**Pull request by pablintino**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date.

### CODE REVIEW

**Comment by pablintino** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by cjeanner** [comment]
We need this patch in order to move forward with the extracted CRC; issues are the ones we want to solve, and hitting randomly, unrelated to the patch itself.

**Pull request merged**
