### PR TITLE
DNM - Checking base-future-extracted-crc

### PR DESCRIPTION
**Pull request by danpawlik**
This commit is veryfing CI jobs by using new base CRC job.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2032

### CODE REVIEW

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
Temporary we can close. It would be re-opened when the new changes for future crc will come.

**Pull request closed without merging**
