### PR TITLE
Address comments from #586

### PR DESCRIPTION
**Pull request by cjeanner**
As discussed in the mentioned PR, a follow-up had to be created in order
to address some comments.

This PR corrects a small typo in a comment/doc, and introduce a new task
file for the network layout validation.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running

### CODE REVIEW

**Review by raukadah — COMMENTED** [review]
@cjeanner can we also drop this https://github.com/openstack-k8s-operators/ci-framework/tree/main/ci_framework/roles/ci_network/vars directory since it is empty?

**Comment by lewisdenny** [comment]
/lgtm
Thanks Cédric!

**Pull request merged**
