### PR TITLE
[Draft] Add horizon test role

### PR DESCRIPTION
**Pull request by rachael-george**
As a pull request owner and reviewers, I checked that:
- [ ] Appropriate testing is done and actually running
- [ ] Appropriate documentation exists and/or is up-to-date:
  - [ ] README in the role
  - [ ] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by tosky** [comment]
I would suggest to integrate with test-operator instead - we are moving into that direction and tempest and tobiko are already covered.

**Comment by ashu-011** [comment]
> I would suggest to integrate with test-operator instead - we are moving into that direction and tempest and tobiko are already covered.

Hi @tosky  , Yes that's right . I had this discussion with Pragadeesh earlier . As discussed in hindsight this role is for short term only and for long term we are going to move in the direction test-operator itself .

**Comment by tosky** [comment]
> > I would suggest to integrate with test-operator instead - we are moving into that direction and tempest and tobiko are already covered.
> 
> Hi @tosky , Yes that's right . I had this discussion with Pragadeesh earlier . As discussed in hindsight this role is for short term only and for long term we are going to move in the direction of test-operator itself .

Do we really need a short and long term? Tobiko users started with their own role, then quickly moved to test-operator and I think everything went fine. I'd argue that the cost of going directly with test operators is not too high and it's going to save significant time later.

**Comment by rachael-george** [comment]
> @rachael-george @tosky heya! is this still relevant? I saw mention of integrating that test suit elsewhere... ?

Yes, we'll integrate it with the test-operator. But I want to keep this open for any changes in the ci-framework repo

**Pull request closed without merging**
