### PR TITLE
Add a simple retries mechanism for os_net_config

### PR DESCRIPTION
**Pull request by pablintino**
Seems that sometimes OSP call may fail, so we can try to alleviate those issues by retrying.

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by pablintino** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Review by raukadah — APPROVED** [review]
/approve

**Pull request merged**
