### PR TITLE
[DNM] Testing podified-multinode-hci-deployment-crc

### PR DESCRIPTION
**Pull request by fultonj**
Ignore

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by fultonj** [comment]
recheck

**Comment by fultonj** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by fultonj** [comment]
I can sanity test with https://github.com/openstack-k8s-operators/ci-framework/pull/2127 instead

**Pull request closed without merging**
