### PR TITLE
Replace zuul-worker with zuul

### PR DESCRIPTION
**Pull request by raukadah**
Currently on CS9 crc image, the default user is zuul-worker. In dependent job, when data is passed from one job to another. then ansible_user_dir is already returned to parent job's user. It causes issues on dependent jobs.

The infra has fixed the crc node user to zuul. This patch makes sure we replace the zuul-worker to zuul at all places.

As a pull request owner and reviewers, I checked that:
- [X] Appropriate testing is done and actually running
- [ ] ~~Appropriate documentation exists and/or is up-to-date:~~
  - [ ] ~~README in the role~~
  - [ ] ~~Content of the docs/source is reflecting the changes~~

### CODE REVIEW

**Review by marios — APPROVED** [review]
lgtm and grep did not reveal any more

**Comment by pablintino** [comment]
Means this that we can get rid off this? https://github.com/openstack-k8s-operators/ci-framework/pull/212

**Comment by raukadah** [comment]
> Means this that we can get rid off this? #212

Yes, The crc snapshot creation is getting automated: https://softwarefactory-project.io/r/c/software-factory/sf-infra/+/28356/ and fixed with zuul user.

**Comment by pablintino** [comment]
> > Means this that we can get rid off this? #212
> 
> Yes, The crc snapshot creation is getting automated: https://softwarefactory-project.io/r/c/software-factory/sf-infra/+/28356/ and fixed with zuul user.

Nice, if you can, when the user is finally gone, create a followup PR to remove that workaround. Thanks!

**Comment by cjeanner** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Pull request merged**
