### PR TITLE
Remove openstack collection from requirements

### PR DESCRIPTION
**Pull request by lewisdenny**
With the final use of the OpenStack collection being removed in this patch, we can stop installing it.

Partial revert: https://github.com/openstack-k8s-operators/ci-framework/pull/1296

Jira: https://issues.redhat.com/browse/OSPRH-7850

### CODE REVIEW

**Comment by lewisdenny** [comment]
recheck

**Review by rebtoor — APPROVED** [review]

**Comment by raukadah** [comment]
/hold 
need steve feedback

**Review by steveb — COMMENTED** [review]
/lgtm

**Pull request merged**
