### PR TITLE
DNM vexxhost API testing

### PR DESCRIPTION
**Pull request by pablintino**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running
- [x] Appropriate documentation exists and/or is up-to-date:
  - [x] README in the role
  - [x] Content of the docs/source is reflecting the changes

### CODE REVIEW

**Comment by rlandy** [comment]
recheck

**Comment by rlandy** [comment]
recheck

**Comment by rlandy** [comment]
recheck

**Comment by pablintino** [comment]
recheck

**Comment by cjeanner** [comment]
recheck

**Comment by rlandy** [comment]
recheck

**Pull request closed without merging**
