### PR TITLE
Add option for run all roles tests

### PR DESCRIPTION
**Pull request by adrianfusco**
Added `TEST_ALL_ROLES` variable for testing all the roles that have tests.

### CODE REVIEW

**Comment by adrianfusco** [comment]
> TEST_ALL_ROLES=yes make molecule



> on running TEST_ALL_ROLES=yes make molecule, it is throwing following error
> 
> ```
> +++ readlink -f scripts/setup_molecule
> ++ dirname /home/chandankumar/src/github.com/openstack-k8s-operators/ci-framework/scripts/setup_molecule
> + export PROJECT_DIR=/home/chandankumar/src/github.com/openstack-k8s-operators/ci-framework/scripts/../
> + PROJECT_DIR=/home/chandankumar/src/github.com/openstack-k8s-operators/ci-framework/scripts/../
> + export ANSIBLE_SKIP_CONFLICT_CHECK=1
> + ANSIBLE_SKIP_CONFLICT_CHECK=1
> + PIP=pip
> + GALAXY=ansible-galaxy
> + COLLECTION_PATH=/usr/share/ansible/collections
> + case ${USE_VENV} in
> scripts/setup_molecule: line 30: USE_VENV: unbound variable
> make: *** [Makefile:25: setup_molecule] Error 1
> ```
> 
> Can you please have a look.

Hello Chandan. Are you executing it with the container created by Cedric? (the tests are gonna be executed through it) I've tested again and it seems to work fine.

**Comment by adrianfusco** [comment]
I've added the required `PYTHON_EXEC` variable located in other scripts but not in `setup_molecule` one.

**Comment by adrianfusco** [comment]
Tested:

```bash
[root@fa4d322eb628 123]# TEST_ALL_ROLES=yes ROLE_DIR=/tmp/123/ci_framework/roles/ MOLECULE_CONFIG=.config/molecule/config_local.yml make molecule

...
+++ readlink -f scripts/run_molecule
++ dirname /tmp/123/scripts/run_molecule
+ PROJECT_DIR=/tmp/123/scripts/../
+ ROLE_DIR=/tmp/123/ci_framework/roles/
+ USE_VENV=yes
+ TEST_ALL_ROLES=yes
+ test -d /tmp/123/ci_framework/roles/
+ pushd /tmp/123/ci_framework/roles/
/tmp/123/ci_framework/roles /tmp/123
++ echo /tmp/123/ci_framework/roles/
++ sed 's|\.\?\./||g'
+ local_roledir=/tmp/123/ci_framework/roles/
++ git diff --name-only 'HEAD^..HEAD' .
+ ROLES_LIST=
+ '[' yes == yes ']'
++ ls -1 /tmp/123/ci_framework/roles/
+ ROLES_LIST=ci_make
+ for rolepath in ${ROLES_LIST}
++ echo ci_make
++ sed 's|/tmp/123/ci_framework/roles/||'
++ cut -f1 -d /
+ role=ci_make
+ echo 'Running molecule against: ci_make'
Running molecule against: ci_make
+ pushd ci_make
/tmp/123/ci_framework/roles/ci_make /tmp/123/ci_framework/roles /tmp/123
+ case ${USE_VENV} in
+ /root/test-python/bin/molecule -c /tmp/123/scripts/../.config/molecule/config_local.yml test
INFO     Found config file /tmp/123/.config/molecule/config.yml
INFO     default scenario test matrix: prepare, converge
INFO     Performing prerun with role_name_check=0...
INFO     Set ANSIBLE_LIBRARY=/root/.cache/ansible-compat/18b06c/modules:/root/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/root/.cache/ansible-compat/18b06c/collections:/root/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/root/.cache/ansible-compat/18b06c/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
INFO     Using /root/.cache/ansible-compat/18b06c/roles/edpm.ci_make symlink to current repository in order to enable Ansible to find the role using its expected full name.
INFO     Running default > prepare
WARNING  Skipping, instances already prepared.
INFO     Running default > converge

PLAY [Converge] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [instance]
```

**Review by raukadah — APPROVED** [review]

**Pull request merged**
