### PR TITLE
Update adoption and base to crc 2.36(OCP 4.15)

### PR DESCRIPTION
**Pull request by lewisdenny**
Jira: https://issues.redhat.com//browse/OSPRH-6868

As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by lewisdenny** [comment]
hmm both failing on networking issues. I think there is an issue with nncp 😢

**Comment by lewisdenny** [comment]
recheck
to be sure

**Comment by lewisdenny** [comment]
recheck

**Comment by lewisdenny** [comment]
recheck

**Comment by lewisdenny** [comment]
Blocked by https://issues.redhat.com/browse/OSPCIX-328

We need https://github.com/openstack-k8s-operators/openstack-operator/pull/832 but that’s blocked on https://github.com/openstack-k8s-operators/openstack-operator/pull/830

**Comment by lewisdenny** [comment]
recheck

**Comment by lewisdenny** [comment]
recheck

**Comment by lewisdenny** [comment]
recheck

Now that [1] is merged and [2] is merged fixing the unrelated adoption failure.

[1] https://github.com/openstack-k8s-operators/ci-framework/pull/1854
[2] https://review.rdoproject.org/r/c/rdo-jobs/+/53454

**Comment by lewisdenny** [comment]
Seem to failing waiting on the dataplane deployment[1], only error I could find was Cinder volume seemed to failed for unknown reason:
`Caught SIGTERM, stopping children` [2]

Seems dataplane deployment didn't even start though. 

[1]https://logserver.rdoproject.org/29/1829/c703ba9d862e0ca24052949e5b6e2fc66baa40b0/github-check/cifmw-data-plane-adoption-osp-17-to-extracted-crc/65a5e2f/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/openstackdataplanedeployments.dataplane.openstack.org/openstack.yaml
[2] https://logserver.rdoproject.org/29/1829/c703ba9d862e0ca24052949e5b6e2fc66baa40b0/github-check/cifmw-data-plane-adoption-osp-17-to-extracted-crc/65a5e2f/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/cinder-volume-volume1-0/logs/cinder-volume.log

**Comment by lewisdenny** [comment]
recheck

**Comment by pablintino** [comment]
@lewisdenny I leave a hold to avoid shipping this on Friday, remove it when you start on Monday :)

**Pull request merged**
