### PR TITLE
Revert "Add Dev-preview workaround to finish EDPM deployment"

### PR DESCRIPTION
**Pull request by raukadah**
As a pull request owner and reviewers, I checked that:
- [x] Appropriate testing is done and actually running

### CODE REVIEW

**Comment by gibizer** [comment]
If this PR is targeting the current main branch of nova- and dataplane-operator then I agree that the extra wait is not needed any more as that was needed only for the dev-preview branch version

**Comment by rlandy** [comment]
We are officially done with dev-preview 1 so ack we can remove it if the wait is not required in master versions

**Comment by rlandy** [comment]
recheck

**Review by rabi — APPROVED** [review]
/lgtm

**Pull request merged**
