### PR TITLE
Fix EDPM instances IPs for VLAN nets

### PR DESCRIPTION
**Pull request by pablintino**

### CODE REVIEW

**Comment by lmiccini** [comment]
`[zuul@compute-bgnnm687-0 ~]$ ip a |grep 172
    inet 172.19.0.100/24 brd 172.19.0.255 scope global vlan22
    inet 172.18.0.100/24 brd 172.18.0.255 scope global vlan21
    inet 172.17.0.100/24 brd 172.17.0.255 scope global vlan20
    inet 172.22.0.100/24 brd 172.22.0.255 scope global vlan25
    inet 172.20.0.100/24 brd 172.20.0.255 scope global vlan23
[zuul@compute-bgnnm687-0 ~]$

[zuul@compute-bgnnm687-1 ~]$ ip a |grep 172
    inet 172.19.0.101/24 brd 172.19.0.255 scope global vlan22
    inet 172.20.0.101/24 brd 172.20.0.255 scope global vlan23
    inet 172.17.0.101/24 brd 172.17.0.255 scope global vlan20
    inet 172.18.0.101/24 brd 172.18.0.255 scope global vlan21
    inet 172.22.0.101/24 brd 172.22.0.255 scope global vlan25`

lgtm, thanks Pablo!

**Review by rebtoor — APPROVED** [review]
/lgtm

**Pull request merged**
